version: "3"
services:
  web:
    volumes:
      - .:/srv/rescue-api
    build: .
    image: rescue-api-image
    container_name: rescue-api-container
    env_file:
      - .env
    ports:
      - "80:80"
    networks:
      - mynetwork
networks:
  mynetwork:
