version: "3"
services:
  web:
    volumes:
      - .:/srv/rescue-api
    build: .
    image: rescue-api-image
    container_name: rescue-api-container
    depends_on:
      - database
    command: ["./wait-for-it.sh", "database:3306"]
    env_file:
      - .env
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - mynetwork
  database:
    image: mysql:8.0.12
    container_name: rescue-api-database-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rescue
    ports:
      - "3307:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
