version: "3"
services:
  web:
    volumes:
      - .:/srv/rescue-api
    build: .
    image: rescue-api-image
    container_name: rescue-api-container
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - mynetwork
  database:
    image: mysql:8.0.12
    container_name: rescue-api-database-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - mynetwork
networks:
  mynetwork:
